application/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('home.urls'), name='home'),  # the app for home page and system authorization
    url(r'^quiz/', include('quiz.urls'), name='quiz'),  # the custom side
    url(r'^admin/', admin.site.urls),
]

home/urls.py
from django.conf.urls import url

from . import views


app_name = 'home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),  # home/main page
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^register/success/$', views.RegisterSuccessView.as_view(), name='success_register'),
    url(r'^settings/$', views.UserSettingsView.as_view(), name='settings'),
    url(r'^change/password/$', views.RestorePasswordRequestView.as_view(), name='change_password'),
]

quiz/urls.py
from django.conf.urls import url

from . import views


app_name = 'quiz'   # namespace for this app
urlpatterns = [
    url(r'^$', views.UserProfileView.as_view(), name='user_profile'),
    url(r'^(?P<type_test_id>\d+)/$', views.quiz_test_view, name='quiz_test'),
]

home/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager


class User(AbstractBaseUser, PermissionsMixin):
    """
    Override base user
    This is the class which describes the standard user
    """
    username = models.CharField(max_length=32, unique=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('is active'), default=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    # Below isn't required fields
    first_name = models.CharField(max_length=32, blank=True, null=True)
    last_name = models.CharField(max_length=32, blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'auth_user'

    def get_short_name(self):
        if self.first_name or self.last_name:
            return ' '.join((self.first_name, self.last_name))
        return self.email

home/forms/user.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=32,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Username'),
                'style': 'width: 350px;'
            }),
        required=True,
        label=''
    )
    password = forms.CharField(
        max_length=32,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password'),
                'style': 'width: 350px;'
            }),
        required=True,
        label=''
    )


class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        max_length=32,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password'),
                'style': 'width: 350px;'
            }),
        required=True,
        label='')
    required_css_class = 'required'

    class Meta:
        exclude = [
            'date_joined', 'last_login',
            'is_active', 'is_staff', 'is_superuser',
            'first_name', 'last_name',
            'groups', 'user_permissions'
        ]
        model = get_user_model()
        labels = {
            'username': '',
            'email': '',
        }
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Username'),
                    'style': 'width: 350px;'
                }),
            'email': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Email'),
                    'style': 'width: 350px;'
                }),
        }
        fields = ('username', 'password', 'email')


class RestorePasswordRequestForm(forms.Form):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Your email'),
                'style': 'width: 350px;'
            }),
        label='',)

home/views.py
import random
import string

from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout, authenticate, login, get_user_model

from .models import User
from home.forms.user import LoginForm, RegisterForm, RestorePasswordRequestForm


def redirect_if_user_login(f):
    # Redirects from home and register pages if the user is already authorized
    def wrap(request, *args, **kwargs):
        if request.user.is_authenticated:
            # return an absolute link
            return HttpResponseRedirect(reverse('quiz:user_profile'))
        else:
            return f(request, *args, **kwargs)
    return wrap


class IndexView(generic.TemplateView):
    template_name = 'home/index.html'


class LoginView(generic.TemplateView):
    form_class = LoginForm
    template_name = 'home/login.html'

    @method_decorator(redirect_if_user_login)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        return self.render_to_response(locals())

    def post(self, request):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(**data)
            if user and user.is_active:
                login(request, user)
                _next = request.GET.get('next', reverse('quiz:user_profile'))
                return HttpResponseRedirect(_next, status=301)
            else:
                errors = [_('LOGIN FAILD')]
        return self.render_to_response(locals())


class LogoutView(generic.View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class RegisterView(generic.FormView):
    form_class = RegisterForm
    template_name = 'home/register.html'
    success_url = '/quiz/'

    @method_decorator(redirect_if_user_login)
    def dispatch(self, request, *args, **kwargs):
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        instance = form.save()
        instance.is_active = True
        instance.set_password(form.cleaned_data['password'])
        instance.save()
        user = authenticate(username=instance.username, password=form.cleaned_data['password'])
        login(self.request, user)
        messages.add_message(self.request, messages.SUCCESS, _('You have successfully registered'))
        return super(RegisterView, self).form_valid(form)


class RegisterSuccessView(generic.TemplateView):
    template_name = 'home/success_register.html'


class UserSettingsView(LoginRequiredMixin, generic.DetailView):
    template_name = 'home/settings.html'
    model = get_user_model()
    context_object_name = 'user'

    def get_object(self, queryset=None):
        return User.objects.get(id=self.request.user.id)


class RestorePasswordRequestView(generic.FormView):
    form_class = RestorePasswordRequestForm
    template_name = 'home/change_password.html'

    def form_valid(self, form):
        email = form.cleaned_data['email']
        new_password = ''.join(map(lambda x: random.choice(string.ascii_letters + string.digits), range(10)))

        user = get_user_model().objects.get(email=email)
        user.set_password(new_password)
        user.save()
        messages.add_message(self.request, messages.SUCCESS,
                             _('Your password is reset. Check email and login.'))
        return HttpResponseRedirect(reverse('home:login'))

home/templates/home/base.html
{% extends "base.html" %}

{% block content %}
{% block popups %}

{% endblock %}
<div class="wrapper">
    <div class="top">
        <div class="wrap">
            <div class="right">
                {% if user %}
                <li><a href="{% url 'quiz:user_profile' %}"> {{ user|capfirst }} </a></li>
                <li><a href="{% url 'home:settings' %}"> Settings </a></li>
                <li><a href="{% url 'home:logout' %}" class="exit" title="logout">Logout</a></li>
                {% endif %}
            </div>
            <div id="logo"></div>
            <a class="btn btn-success" href="{% url 'quiz:user_profile' %}">Main Page</a>
        </div>
    </div>
    <div class="wrap">
        <div class="content">
            <div class="left">
                {% block left %}
                {% endblock %}
            </div>
            <br/>
            {% block user_content %}
            {% endblock %}
        </div>
    </div>
</div>
<br/><br/>
{% endblock %}

home/templates/home/bottom.html
<div id="bottom">
    <div id="footer">
        <a href="https://www.python.org/"><img src="/static/home/img/logos/1.png"/></a>
        <a href="https://www.djangoproject.com/"><img src="/static/home/img/logos/2.png"/></a>
        <a href="https://vk.com/"><img src="/static/home/img/logos/3.png"/></a>
    </div>
    <div class="right">
        <div class="company">
            &copy; 2025. Jack Daniel's Tennessee Whiskey.<br/>
            <b>Sergey Lobanov - Earthling</b>
        </div>

        <div class="links">
            <a href="https://vk.com/stratopedarx" class="contacts">Contacts</a>
            <a href="https://www.youtube.com/" class="sitemap">YouTube</a>
            <a href="https://www.google.ru/" class="help">Help</a>
        </div>
    </div>
</div>

home/templates/home/change_password.html
{% extends 'home/base.html' %}
{% load i18n %}

{% block user_content %}
 <ul class="errorlist">
    {% for e in  errors %}
       <li>{{ e }}</li>
    {% endfor %}
     </ul>
<form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" class="btn btn-success" value="{% trans 'Restore pasword' %}">
</form>
<br /><br /><br /><br /><br /><br /><br /><br /><br />
<br /><br /><br /><br /><br /><br /><br /><br /><br />
<br /><br /><br /><br />
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}

{% block content %}
<div id="head">
    <img src="/static/home/img/logos/main_logo.jpg" title="Test yourself, man"  alt="Test yourself, man"/><br/>
    <h2><font size="7" color="blue">Test yourself, man</font></h2>
    <h3><font color="">The best service for checking your mind</font></h3>
    <img src="/static/home/gif/smail.gif" title="Test yourself, man" alt="Test yourself, man" style="margin-top: 10px;"/>

    <div class="form">
        <form action="{% url 'home:login' %}" class="form form-inline" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="username" id="id_username" class="form-control" placeholder="Login" />
            </div>
            <div class="form-group">
                <input type="password" name="password"  id="id_password" class="form-control" placeholder="Password" />
            </div>
            <div class="form-group">
                <input type="submit" value="LOGIN" class="btn"/>
            </div>
        </form>
        <div class="btns">
            <a href="https://www.google.ru/">Login via Google+</a>
            <br/>
            <a href="https://vk.com/">Login via Instagram</a>
            <br/>
            <a href="https://www.facebook.com">Login via Facebook</a>
            <br/>
            <a href="{% url 'home:register' %}" class="btn reg">Registration</a>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/login.html
{% extends 'home/base.html' %}
{% load i18n %}

{% block user_content %}
    <ul class="errorlist">
    {% for e in  errors %}
       <li>{{ e }}</li>
    {% endfor %}
     </ul>
    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" class="btn btn-success" value="{% trans 'Login' %}">
        <a href='{% url "home:register" %}' class="btn btn-success">{% trans 'Registration' %}  </a>
        <a href='{% url "home:change_password" %}' class="btn btn-success">{% trans "Restore password" %}</a>
    </form>
    <br /> {# \n #}
    <a href="https://vk.com/" class="btn">Login via VK</a>
    <br />
    <a href="https://www.google.ru/" class="btn">Login via Google+</a>
    <br />
    <a href="https://www.facebook.com" class="btn">Login via Facebook</a>
{% endblock %}

home/templates/home/register.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    <form method="post">
            <br /><br />
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn btn-success" value="{% trans 'REGISTRATION' %}">
        </form>
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    <br />
{% endblock %}

home/templates/home/settings.html
{% extends "base.html" %}
{% block content %}
<h2>Hello {{ user|capfirst }}. This page is developed at the moment.</h2>
<h2>We so apologize. Stay here. Be healthy.</h2>
<br/>
<p class="fig"><img src="/static/home/img/cat.png"/><p>
    <br/><br/><br/>
{% endblock %}

home/templates/home/success_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SUCCESS</title>
</head>
<body>

</body>
</html>